/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package observador;

import java.util.Observable;
import observable.Temperatura;

/**
 *
 * @author alex
 */
public class PantallaTemperatura extends ObservadorTemperatura implements Runnable {

    
    /**
     * Constructor
     * @param t 
     */
    public PantallaTemperatura(Temperatura t) {
        super(t);
        initComponents();
    }
    
    @Override
    public void run() {
        // TODO
    }

    @Override
    public String toString() {
        return "PantallaTemperatura: " + miTemperatura;
    }

    @Override
    public void update(Observable o, Object arg) {
        super.update(o, arg);
        this.etiqueta_temp.setText(this.miTemperatura+"ºC");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiqueta_temp = new javax.swing.JLabel();

        etiqueta_temp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_temp.setText("--.-ºC");
        etiqueta_temp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        etiqueta_temp.setPreferredSize(new java.awt.Dimension(100, 20));
        add(etiqueta_temp);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiqueta_temp;
    // End of variables declaration//GEN-END:variables
}
