/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author alex
 */
public class BotonCambio extends javax.swing.JPanel {

    /**
     * Creates new form BotonCambio
     */
    public BotonCambio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiqueta_temp = new javax.swing.JLabel();
        textField_temp = new javax.swing.JTextField();
        boton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(150, 60));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        etiqueta_temp.setText("0,00ºC");
        add(etiqueta_temp);

        textField_temp.setText("0,00ºC");
        textField_temp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_tempActionPerformed(evt);
            }
        });
        add(textField_temp);

        boton.setText("Cambiar");
        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMouseClicked(evt);
            }
        });
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        add(boton);
    }// </editor-fold>//GEN-END:initComponents

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        etiqueta_temp.setText(textField_temp.getText());
    }//GEN-LAST:event_botonActionPerformed

    private void textField_tempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_tempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_tempActionPerformed

    private void botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMouseClicked
        etiqueta_temp.setText(textField_temp.getText());
    }//GEN-LAST:event_botonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JLabel etiqueta_temp;
    private javax.swing.JTextField textField_temp;
    // End of variables declaration//GEN-END:variables
}
