/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JFrame;


/**
 *
 * @author pablorobles
 */
public class Simulador extends JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public Simulador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantallaTemperatura = new javax.swing.JPanel();
        barraTemperatura = new javax.swing.JProgressBar();
        panelInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        temperaturaCambio = new javax.swing.JTextField();
        temperaturaActual = new javax.swing.JTextField();
        botonCambio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pantallaTemperatura.setLayout(new java.awt.BorderLayout());
        pantallaTemperatura.add(barraTemperatura, java.awt.BorderLayout.CENTER);

        panelInfo.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setText("Temperatura");
        panelInfo.add(jLabel1);

        temperaturaCambio.setText("-- ºC");
        panelInfo.add(temperaturaCambio);

        temperaturaActual.setText("-- ºC");
        panelInfo.add(temperaturaActual);

        botonCambio.setText("Cambiar");
        panelInfo.add(botonCambio);

        pantallaTemperatura.add(panelInfo, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pantallaTemperatura, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraTemperatura;
    private javax.swing.JButton botonCambio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel pantallaTemperatura;
    private javax.swing.JTextField temperaturaActual;
    private javax.swing.JTextField temperaturaCambio;
    // End of variables declaration//GEN-END:variables
}
