package GUI;

import controlVelocidad.EstadoMotor;
import java.awt.Color;

/**
 *
 * @author pablorobles
 */
public class Controles extends javax.swing.JFrame {
    
    protected EstadoMotor estado = EstadoMotor.APAGADO;
    
    /**
     * Creates new form VentanaControl
     */
    public Controles() {
        initComponents();
        this.setVisible(true);
    }

    public EstadoMotor getEstado() {
        return estado;
    }

    public void setEstado(EstadoMotor estado) {
        this.estado = estado;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_mandos = new javax.swing.JPanel();
        panel_estado = new javax.swing.JPanel();
        etiqueta_estado = new javax.swing.JLabel();
        panel_botones = new javax.swing.JPanel();
        boton_encendido = new javax.swing.JToggleButton();
        boton_acelerador = new javax.swing.JButton();
        boton_freno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_mandos.setBorder(javax.swing.BorderFactory.createTitledBorder("mandos"));
        panel_mandos.setLayout(new java.awt.GridLayout(2, 1));

        panel_estado.setLayout(new java.awt.BorderLayout());

        etiqueta_estado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_estado.setText("APAGADO");
        etiqueta_estado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        etiqueta_estado.setOpaque(true);
        panel_estado.add(etiqueta_estado, java.awt.BorderLayout.CENTER);

        panel_mandos.add(panel_estado);

        panel_botones.setLayout(new java.awt.GridLayout(1, 3));

        boton_encendido.setText("ENCENDER");
        boton_encendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_encendidoActionPerformed(evt);
            }
        });
        panel_botones.add(boton_encendido);

        boton_acelerador.setText("ACELERAR");
        boton_acelerador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton_aceleradorMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                boton_aceleradorMouseReleased(evt);
            }
        });
        panel_botones.add(boton_acelerador);

        boton_freno.setText("FRENAR");
        boton_freno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton_frenoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                boton_frenoMouseReleased(evt);
            }
        });
        panel_botones.add(boton_freno);

        panel_mandos.add(panel_botones);

        getContentPane().add(panel_mandos, java.awt.BorderLayout.PAGE_START);
        panel_mandos.getAccessibleContext().setAccessibleName("Mandos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_encendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_encendidoActionPerformed
        if(this.etiqueta_estado.getText().equals("APAGADO")){
            this.etiqueta_estado.setText("ENCENDIDO");
            this.setEstado(EstadoMotor.ENCENDIDO);
            this.boton_encendido.setText("APAGAR");
            this.boton_encendido.setForeground(Color.red);
        }else{
            this.etiqueta_estado.setText("APAGADO");
            this.setEstado(EstadoMotor.APAGADO);
            this.boton_encendido.setText("ENCENDER");
            this.boton_encendido.setForeground(Color.green);
        }
    }//GEN-LAST:event_boton_encendidoActionPerformed

    private void boton_aceleradorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_aceleradorMousePressed
        if(this.etiqueta_estado.getText().equals("ENCENDIDO")){
            this.etiqueta_estado.setText("ACELERANDO");
            this.setEstado(EstadoMotor.ACELERANDO);
            this.etiqueta_estado.setForeground(Color.red);
            this.boton_acelerador.setText("Soltar acelerador");
            this.boton_acelerador.setForeground(Color.red);
        }
    }//GEN-LAST:event_boton_aceleradorMousePressed

    private void boton_aceleradorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_aceleradorMouseReleased
        if(this.etiqueta_estado.getText().equals("ACELERANDO")){  
            this.etiqueta_estado.setText("ENCENDIDO");
            this.setEstado(EstadoMotor.ENCENDIDO);
            this.etiqueta_estado.setForeground(Color.black);
            this.boton_acelerador.setText("ACELERAR");
            this.boton_acelerador.setForeground(Color.black);
        }
    }//GEN-LAST:event_boton_aceleradorMouseReleased

    private void boton_frenoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_frenoMousePressed
        if(this.etiqueta_estado.getText().equals("ENCENDIDO")){
            this.etiqueta_estado.setText("FRENANDO");
            this.setEstado(EstadoMotor.FRENANDO);
            this.etiqueta_estado.setForeground(Color.red);
            this.boton_freno.setText("Soltar freno");
            this.boton_freno.setForeground(Color.red);
        }
    }//GEN-LAST:event_boton_frenoMousePressed

    private void boton_frenoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_frenoMouseReleased
        if(this.etiqueta_estado.getText().equals("FRENANDO")){
            this.etiqueta_estado.setText("ENCENDIDO");
            this.setEstado(EstadoMotor.ENCENDIDO);
            this.etiqueta_estado.setForeground(Color.black);
            this.boton_freno.setText("FRENAR");
            this.boton_freno.setForeground(Color.black);
        }
    }//GEN-LAST:event_boton_frenoMouseReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Controles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Controles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Controles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Controles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Controles().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_acelerador;
    private javax.swing.JToggleButton boton_encendido;
    private javax.swing.JButton boton_freno;
    private javax.swing.JLabel etiqueta_estado;
    private javax.swing.JPanel panel_botones;
    private javax.swing.JPanel panel_estado;
    private javax.swing.JPanel panel_mandos;
    // End of variables declaration//GEN-END:variables
}
