/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.CuentaRevoluciones;
import GUI.CuentaKilometros;

/**
 *
 * @author pablorobles
 */
public class Salpicadero extends javax.swing.JPanel {
    
    
    /**
     * Creates new form Salpicadero
     */
    public Salpicadero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        velocimetro = new GUI.Velocimetro();
        cuentaKilometros = new GUI.CuentaKilometros();
        cuentaRevoluciones = new GUI.CuentaRevoluciones();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Salpicadero"));
        setLayout(new java.awt.GridLayout(3, 1));
        add(velocimetro);
        add(cuentaKilometros);
        add(cuentaRevoluciones);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.CuentaKilometros cuentaKilometros;
    private GUI.CuentaRevoluciones cuentaRevoluciones;
    private GUI.Velocimetro velocimetro;
    // End of variables declaration//GEN-END:variables
}
