/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author pablorobles
 */
public class Velocimetro extends javax.swing.JPanel {

    /**
     * Creates new form Velocimetro
     */
    public Velocimetro() {
        initComponents();
    }
    
    public void actualizar(double v){
        this.etiqueta_velocidad.setText(""+v);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_kmh = new javax.swing.JPanel();
        etiqueta_velocidad = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Velocímetro"));
        setLayout(new java.awt.BorderLayout());

        panel_kmh.setBorder(javax.swing.BorderFactory.createTitledBorder("km/h"));
        panel_kmh.setLayout(new java.awt.BorderLayout());

        etiqueta_velocidad.setText("00.00");
        panel_kmh.add(etiqueta_velocidad, java.awt.BorderLayout.CENTER);

        add(panel_kmh, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiqueta_velocidad;
    private javax.swing.JPanel panel_kmh;
    // End of variables declaration//GEN-END:variables
}
