package GUI;

import java.awt.BorderLayout;
import java.awt.Component;

/**
 *
<<<<<<< HEAD
 * @author pablorobles
=======
 * @author alex
>>>>>>> origin/master
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
<<<<<<< HEAD
=======
     * @param c
     * @param titulo
>>>>>>> origin/master
     */
    public Ventana(Component c, String titulo) {
        super();
        initComponents();
        setTitle(titulo);
        setLayout(new BorderLayout());
        add(c, BorderLayout.CENTER);
        pack();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
<<<<<<< HEAD

=======
>>>>>>> origin/master
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
