/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author pablorobles
 */
public class PruebaInterfaz extends javax.swing.JPanel {

    /**
     * Creates new form PruebaInterfaz
     */
    public PruebaInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_principal = new javax.swing.JPanel();
        panelVelocidad = new javax.swing.JPanel();
        radial2Lcd1 = new eu.hansolo.steelseries.gauges.Radial2Lcd();
        displaySingle1 = new eu.hansolo.steelseries.gauges.DisplaySingle();
        panelCombustible = new javax.swing.JPanel();
        radial1Square1 = new eu.hansolo.steelseries.gauges.Radial1Square();
        displaySingle2 = new eu.hansolo.steelseries.gauges.DisplaySingle();
        panelControles = new javax.swing.JPanel();
        panelMecanico = new javax.swing.JPanel();
        panelInfoMec = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(500, 600));
        setLayout(new java.awt.GridLayout(4, 1));

        panel_principal.setBorder(javax.swing.BorderFactory.createTitledBorder("Principal"));
        panel_principal.setPreferredSize(new java.awt.Dimension(400, 400));
        panel_principal.setLayout(new java.awt.BorderLayout());

        panelVelocidad.setPreferredSize(new java.awt.Dimension(212, 400));
        panelVelocidad.setLayout(new java.awt.BorderLayout());
        panelVelocidad.add(radial2Lcd1, java.awt.BorderLayout.NORTH);
        panelVelocidad.add(displaySingle1, java.awt.BorderLayout.SOUTH);

        panel_principal.add(panelVelocidad, java.awt.BorderLayout.WEST);

        panelCombustible.setLayout(new java.awt.BorderLayout());
        panelCombustible.add(radial1Square1, java.awt.BorderLayout.CENTER);
        panelCombustible.add(displaySingle2, java.awt.BorderLayout.SOUTH);

        panel_principal.add(panelCombustible, java.awt.BorderLayout.EAST);

        add(panel_principal);

        panelControles.setBorder(javax.swing.BorderFactory.createTitledBorder("Controles"));
        panelControles.setPreferredSize(new java.awt.Dimension(400, 200));

        javax.swing.GroupLayout panelControlesLayout = new javax.swing.GroupLayout(panelControles);
        panelControles.setLayout(panelControlesLayout);
        panelControlesLayout.setHorizontalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );
        panelControlesLayout.setVerticalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );

        add(panelControles);

        panelMecanico.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones Mecanico"));

        javax.swing.GroupLayout panelMecanicoLayout = new javax.swing.GroupLayout(panelMecanico);
        panelMecanico.setLayout(panelMecanicoLayout);
        panelMecanicoLayout.setHorizontalGroup(
            panelMecanicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );
        panelMecanicoLayout.setVerticalGroup(
            panelMecanicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );

        add(panelMecanico);

        panelInfoMec.setBorder(javax.swing.BorderFactory.createTitledBorder("Info. Mecanico"));

        javax.swing.GroupLayout panelInfoMecLayout = new javax.swing.GroupLayout(panelInfoMec);
        panelInfoMec.setLayout(panelInfoMecLayout);
        panelInfoMecLayout.setHorizontalGroup(
            panelInfoMecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );
        panelInfoMecLayout.setVerticalGroup(
            panelInfoMecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );

        add(panelInfoMec);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eu.hansolo.steelseries.gauges.DisplaySingle displaySingle1;
    private eu.hansolo.steelseries.gauges.DisplaySingle displaySingle2;
    private javax.swing.JPanel panelCombustible;
    private javax.swing.JPanel panelControles;
    private javax.swing.JPanel panelInfoMec;
    private javax.swing.JPanel panelMecanico;
    private javax.swing.JPanel panelVelocidad;
    private javax.swing.JPanel panel_principal;
    private eu.hansolo.steelseries.gauges.Radial1Square radial1Square1;
    private eu.hansolo.steelseries.gauges.Radial2Lcd radial2Lcd1;
    // End of variables declaration//GEN-END:variables
}
