/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.MonitorMecanico;

import GUI.ObservadorMotor;
import java.util.Observable;

/**
 *
 * @author alex
 */
public class Combustible extends ObservadorMotor {
    

    /**
     * Creates new form Combustible
     */
    public Combustible() {
        initComponents();
    }
    
    @Override
    public void update(Observable o, Object arg) {
        textoVar.setText( ""+miObservable.getConsumo() );
        combustibleBarra.setValue((int) miObservable.getCombustible());
        combustibleBarra.setString(miObservable.getCombustible() + " litros");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFijo = new javax.swing.JLabel();
        textoVar = new javax.swing.JLabel();
        textUnidad = new javax.swing.JLabel();
        combustibleBarra = new javax.swing.JProgressBar();
        boton = new javax.swing.JButton();

        textFijo.setText("Consumo: ");
        add(textFijo);

        textoVar.setText("00.00");
        add(textoVar);

        textUnidad.setText("l/100Km");
        add(textUnidad);

        combustibleBarra.setMaximum(75);
        combustibleBarra.setToolTipText("");
        combustibleBarra.setStringPainted(true);
        add(combustibleBarra);

        boton.setText("Respostar");
        add(boton);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JProgressBar combustibleBarra;
    private javax.swing.JLabel textFijo;
    private javax.swing.JLabel textUnidad;
    private javax.swing.JLabel textoVar;
    // End of variables declaration//GEN-END:variables
}
