package GUI;

import java.util.Observable;

/**
 *
 * @author pablorobles
 */
public class CuentaKilometrosSteelSeries extends ObservadorMotor {


    public CuentaKilometrosSteelSeries() {
        initComponents();
    }

    
    @Override
    public void update(Observable o, Object arg) {        
        this.displayKm_rec.setValue(miObservable.getDistanciaRecorrida());
        this.displayKm_total.setValue(miObservable.getDistanciaRecorrida());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_cuentaRec = new javax.swing.JPanel();
        displayKm_rec = new eu.hansolo.steelseries.gauges.DisplaySingle();
        panel_cuentaTotal = new javax.swing.JPanel();
        displayKm_total = new eu.hansolo.steelseries.gauges.DisplaySingle();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Cuentakilómetros"));
        setLayout(new java.awt.GridLayout(2, 1));

        panel_cuentaRec.setBorder(javax.swing.BorderFactory.createTitledBorder("Contador reciente"));
        panel_cuentaRec.setLayout(new java.awt.BorderLayout());

        displayKm_rec.setUnitString("km");
        panel_cuentaRec.add(displayKm_rec, java.awt.BorderLayout.PAGE_END);

        add(panel_cuentaRec);

        panel_cuentaTotal.setBorder(javax.swing.BorderFactory.createTitledBorder("Contador total"));
        panel_cuentaTotal.setLayout(new java.awt.BorderLayout());

        displayKm_total.setUnitString("km");
        panel_cuentaTotal.add(displayKm_total, java.awt.BorderLayout.PAGE_END);

        add(panel_cuentaTotal);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eu.hansolo.steelseries.gauges.DisplaySingle displayKm_rec;
    private eu.hansolo.steelseries.gauges.DisplaySingle displayKm_total;
    private javax.swing.JPanel panel_cuentaRec;
    private javax.swing.JPanel panel_cuentaTotal;
    // End of variables declaration//GEN-END:variables
}
