package GUI;

import java.util.Observable;

/**
 *
 * @author pablorobles
 */
public class VelocimetroSteelSeries extends ObservadorMotor {
    
    
    public VelocimetroSteelSeries() {
        initComponents();        
    }

    
    @Override
    public void update(Observable o, Object arg) {
        this.radial2Lcd1.setValue(miObservable.getVelocidad());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subpanelVelocidadA = new javax.swing.JPanel();
        radial2Lcd1 = new eu.hansolo.steelseries.gauges.Radial2Lcd();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Velocímetro"));
        setMaximumSize(new java.awt.Dimension(250, 250));
        setMinimumSize(new java.awt.Dimension(250, 250));
        setPreferredSize(new java.awt.Dimension(250, 250));
        setLayout(new java.awt.BorderLayout());

        radial2Lcd1.setMaxValue(150.0);
        radial2Lcd1.setMinimumSize(null);
        radial2Lcd1.setTitle("Velocidad");
        radial2Lcd1.setUnitString("km/h");
        radial2Lcd1.setValueTickPeriod(20);
        subpanelVelocidadA.add(radial2Lcd1);

        add(subpanelVelocidadA, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eu.hansolo.steelseries.gauges.Radial2Lcd radial2Lcd1;
    private javax.swing.JPanel subpanelVelocidadA;
    // End of variables declaration//GEN-END:variables
}
