package GUI;

import GUI.SCAV.ControlesSCAV;
import controlAutomatico.ControlAutomatico;
import controlVelocidad.Filtros.FiltroCalcularRPM;
import controlVelocidad.Filtros.FiltroRozamiento;
import controlVelocidad.Cliente;
import controlVelocidad.GestorFiltros;
import controlVelocidad.Objetivo;

/**
 *
 * @author alex
 */
public class VentanaPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        Objetivo motor = new Objetivo();
        GestorFiltros gestor = new GestorFiltros(motor);
        Cliente controlador = new Cliente(gestor);
        
        /****/
        
        FiltroCalcularRPM filtro_velocidad = new FiltroCalcularRPM();
        FiltroRozamiento filtro_rozamiento = new FiltroRozamiento();
        gestor.setFiltro(filtro_velocidad);
        gestor.setFiltro(filtro_rozamiento);
        
        /****/
        
        salpicadero.setObjetivo(motor);        
        controles.setControlador(controlador);
        monitorMecanico.setObjetivo(motor);
        
        /****/
        
        ControlAutomatico scav = ControlAutomatico.getInstancia(controles);
        scav.setObservable(motor);
        controlesSCAV.setObservable(scav);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabsPanel = new javax.swing.JTabbedPane();
        swingPanel = new javax.swing.JPanel();
        salpicadero = new GUI.Salpicadero();
        controles = new GUI.Controles();
        monitorMecanico = new GUI.MonitorMecanico.MonitorMecanico();
        controlesSCAV = new GUI.SCAV.ControlesSCAV();
        medidoresPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1024, 768));
        setLayout(new java.awt.BorderLayout());

        swingPanel.setPreferredSize(new java.awt.Dimension(1024, 768));
        swingPanel.setLayout(new java.awt.BorderLayout());
        swingPanel.add(salpicadero, java.awt.BorderLayout.CENTER);
        swingPanel.add(controles, java.awt.BorderLayout.PAGE_START);
        swingPanel.add(monitorMecanico, java.awt.BorderLayout.LINE_END);
        swingPanel.add(controlesSCAV, java.awt.BorderLayout.PAGE_END);

        tabsPanel.addTab("Swing", null, swingPanel, "Interfaz con componentes Swing");
        swingPanel.getAccessibleContext().setAccessibleName("");

        tabsPanel.addTab("SteelSeries", medidoresPanel);

        add(tabsPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.Controles controles;
    private GUI.SCAV.ControlesSCAV controlesSCAV;
    private javax.swing.JPanel medidoresPanel;
    private GUI.MonitorMecanico.MonitorMecanico monitorMecanico;
    private GUI.Salpicadero salpicadero;
    private javax.swing.JPanel swingPanel;
    private javax.swing.JTabbedPane tabsPanel;
    // End of variables declaration//GEN-END:variables
}
